######################################################################
# Automatically generated by qmake (3.1) Fri Sep 30 17:13:33 2022
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

DEFINES += QT_DEPRECATED_WARNINGS
CONFIG += warn_off
CONFIG += c++11
QT += concurrent
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Directories
SUBDIRS += \
    Sensor \
    Measure \
    mainApp