######################################################################
# Automatically generated by qmake (3.1) Fri Sep 30 16:58:43 2022
######################################################################

TEMPLATE = lib
TARGET = Sensor
CONFIG += staticlib


INCLUDEPATH += . 


# Input
HEADERS += i2cworker.h imuworker.h i2c/i2c.h imu/JY901.h
SOURCES += i2cworker.cpp imuworker.cpp i2c/i2c.c imu/JY901.c
